### ISSUE TITLE
setting min-date to smallest representable date causes an infinite loop

### ISSUE THREAD

**Issue by ZeroIndice** [bendavis78/paper-date-picker#93] opened 2016-03-15 20:32 UTC
I have code that imperatively changes the min-date to "new Date(-8640000000000000)".  However, on the _dateChanged handler in paper-calendar.html, calling date.setHours(0,0,0,0) results in an invalid date.  The event handler gets called again with this invalid value.  It then tries to revert to the "oldValue" which is the same minimum representable date, resulting in an infinite loop.

**Comment by bendavis78** [comment] 2016-04-17 17:32
Duplicate of #81

**Closed by bendavis78** 2016-04-17 17:32 UTC
Labels: duplicate
