### ISSUE TITLE
Start month

### ISSUE THREAD

**Issue by steunix** [bendavis78/paper-date-picker#8] opened 2015-06-30 12:36 UTC
Hi, excellent work, first of all. I just suggest that the initial month of the calendar should be the one of the initial date: starting always from January is mostly impractical

**Comment by bendavis78** [comment] 2015-07-04 21:49
Hmm, it should automatically scroll to the selected month on open. That's a bug.

**Comment by suexID** [comment] 2015-07-23 15:34
We're experiencing this too. :)

**Comment by gulyasfeccferenc** [comment] 2015-07-23 15:35
I got the same problem. Hope you find tha way to eliminate this issue soon

**Comment by gulyasfeccferenc** [comment] 2015-07-27 07:44
Woohoo! Thanks for the quick response. After your fix, its work now.

**Comment by jasongardnerlv** [comment] 2015-07-30 17:31
Seems that it ignores the scrollTo as it is not sized yet (offsetHeight = 0).  I worked around for now with:
```
_showDialog: function() {
  this.$.dialog.toggle();
  this.async(function() {
    this.$.picker.$.calendar.updateSize();
  }.bind(this));
},
```

**Comment by JaySunSyn** [comment] 2015-08-10 10:01
samer here.

**Comment by Compufreak345** [comment] 2015-08-12 14:14
@jasongardnerlv Thanks, that helped! Unfortunately it scrolled to August whereas the selected date was July :0 (I use de locale if it makes any difference)

**Comment by bendavis78** [comment] 2015-09-20 00:28
This should have been fixed since 1.0.3. Are you still seeing an issue? If so, can you provide steps to reproduce?

**Comment by bendavis78** [comment] 2015-11-02 23:48
Closing for now. Let me know if anyone's still experiencing issues.

**Closed by bendavis78** 2015-11-02 23:48 UTC
Labels: pending repsonse
