### ISSUE TITLE
Uncaught RangeError in 1.1.3

### ISSUE THREAD

**Issue by akeemphilbert** [bendavis78/paper-date-picker#92] opened 2016-03-14 17:16 UTC
I inadvertently upgraded to v1.1.3 and i started getting an Uncaught RangeError: Maximum call stack size exceeded. This occurred by simply setting a date to the content (even if it was a new date object). 
Line 606 in paper-calendar.html seems to be where the trouble begins. 

I had to revert to v1.1.2. If it helps I'm using polymer version 1.3.1

**Comment by 32graham** [comment] 2016-03-14 19:12
I'm seeing the same problem after upgrading to v1.1.3.

**Comment by bendavis78** [comment] 2016-04-17 17:31
Duplicate of #81

**Closed by bendavis78** 2016-04-17 17:31 UTC
Labels: duplicate
