### ISSUE TITLE
Dialog style breaks when nested in another element.

### ISSUE THREAD

**Issue by curtiscovington** [bendavis78/paper-date-picker#97] opened 2016-03-24 20:23 UTC
I was attempting to create a paper-date-picker-input element and noticed that the style breaks if the dialog is included as part of another element.

**Comment by bendavis78** [comment] 2016-04-17 18:16
Hi, can you provide an example? You can use this plunkr as a starting point: http://plnkr.co/edit/9c787GHiBzX7zI5x6gsX

**Comment by bendavis78** [comment] 2016-05-24 17:16
Closing due to no-response. Feel free to re-open if you're able to provide steps to reproduce.

**Closed by bendavis78** 2016-05-24 17:16 UTC
Labels: can't reproduce
