### ISSUE TITLE
Too large on mobile devices

### ISSUE THREAD

**Issue by SMEmp** [bendavis78/paper-date-picker#120] opened 2016-06-24 20:16 UTC
When using `<paper-date-picker>` on a mobile device, large sections of the datepicker are unavailable to interact with.

This can be reproduced on desktop Chrome by bringing up the developer console, and clicking the `toggle-device-toolbar` icon in the top left corner.  From there either shrink the page yourself or choose `Responsive` from the top and click the center most division, labeled `Mobile-S`.

A slightly stripped down example of how I'm using this component on my page.

``` html
<paper-dialog on-iron-overlay-closed="dismissDialog">
    <paper-date-picker></paper-date-picker>
    <div class="buttons">
        <paper-button dialog-dismiss>Cancel</paper-button>
        <paper-button dialog-confirm>OK</paper-button>
    </div>
</paper-dialog>
```

**Comment by web-padawan** [comment] 2016-08-05 14:29
@SMEmp this is due to the standard `paper-dialog` margin property: `margin: 24px 40px;`

You can override that by setting this: 
```css
            :host .paper-date-picker-dialog {
                margin: 0;
            }
```

**Comment by bendavis78** [comment] 2016-08-07 20:50
@SMEmp not seeing what you're seeing, even on iPhone 5: 

![image](https://cloud.githubusercontent.com/assets/324392/17465199/9fd1a048-5cb6-11e6-9278-4ea89cd32913.png)

**Comment by ajambrovic** [comment] 2016-08-14 17:38
Hi Ben, I have the same problem, you can check out the code at https://github.com/ajambrovic/reminderpolymer (Reminders functionality) - if it works for you, I can provide more data about my setup.

**Comment by Mrboutte** [comment] 2016-10-10 00:41
![image](https://cloud.githubusercontent.com/assets/6290747/19225039/adc97280-8e60-11e6-9762-890c5ef057d5.png)

stretches off the card view. Not sure what I'm doing wrong, I've tried the steps above

**Comment by Mrboutte** [comment] 2016-10-10 01:56
Here's the fix:

#date-picker {
                position: inherit;
                display: flex;
            }

![image](https://cloud.githubusercontent.com/assets/6290747/19225459/35bf697e-8e6b-11e6-9878-11520eb7c0c4.png)

**Comment by intcreator** [comment] 2016-12-06 22:42
@Mrboutte's hack worked for me, but it would be nice if this was implemented by default.

**Comment by dasurid** [comment] 2017-02-13 03:14
Ben,

I noticed that you seem to be using a desktop based browser set to responsive mode (iPhone 5) to prove that you can't reproduce the problem. 

I too have the same issue on mobile devices with both your date picker and time picker elements. They work perfectly in a desktop environment, and also work perfectly when testing with Chrome and Firefox Developer Edition set to responsive mode, but when tested in an actual device the result is as the others have reported. 

I have applied the 'fixes' suggested but to no avail.  I am testing with an Android 6.0.1 phone with a screen resolution of 480 x 854 and yet the picker doesn't fit into the viewport width.

**Comment by bendavis78** [comment] 2017-07-09 23:14
There have been quite a few changes recently. Can you re-test and see if this is still an issue?

**Comment by admwx7** [comment] 2017-09-18 23:25
ping @SMEmp 

If this is still an issue for you with the latest build, please let me know, otherwise I'll be closing out this issue in the near future.

**Comment by SMEmp** [comment] 2017-09-19 20:09
Apologies, I'm in crunch mode right now and honestly don't have the spare time.  My projects that I was evaluating this datepicker for ended up using [Pikaday](https://github.com/dbushell/Pikaday) instead.

I can take a look when I get some time to cool off, but I unfortunately don't know when that will be.  However you want to handle this issue is up to you.

**Comment by admwx7** [comment] 2017-09-19 20:22
Going to close this out, if anyone has this issue again, please screenshot it with the browser(s) and device(s) affected and either re-open or create a new issue

**Closed by admwx7** 2017-09-19 20:22 UTC
Labels: can't reproduce, pending repsonse
