### ISSUE TITLE
Animation exception thrown when year is clicked

### ISSUE THREAD

**Issue by petearvanitis** [bendavis78/paper-date-picker#156] opened 2016-11-02 11:22 UTC
This is reproducible on the demo page.  If you click on the year, the following exception is thrown. In addition, the year list is not shown. If you click on the date the calendar is not redrawn (just a white background).

<pre>
Uncaught TypeError: Failed to execute 'animate' on 'Element': 'function (a){return a}' is not a valid value for easing
    at Object.b.newUnderlyingAnimationForKeyframeEffect (http://bendavis78.github.io/paper-date-picker/web-animations-js/web-animations-next-lite.min.js:16:7609)
    at b.Animation._rebuildUnderlyingAnimation (http://bendavis78.github.io/paper-date-picker/web-animations-js/web-animations-next-lite.min.js:15:31989)
    at b.Animation (http://bendavis78.github.io/paper-date-picker/web-animations-js/web-animations-next-lite.min.js:15:31032)
    at b.AnimationTimeline._play (http://bendavis78.github.io/paper-date-picker/web-animations-js/web-animations-next-lite.min.js:15:30159)
    at Object.b.newUnderlyingAnimationForGroup (http://bendavis78.github.io/paper-date-picker/web-animations-js/web-animations-next-lite.min.js:16:12228)
    at b.Animation._rebuildUnderlyingAnimation (http://bendavis78.github.io/paper-date-picker/web-animations-js/web-animations-next-lite.min.js:15:32192)
    at b.Animation (http://bendavis78.github.io/paper-date-picker/web-animations-js/web-animations-next-lite.min.js:15:31032)
    at b.AnimationTimeline._play (http://bendavis78.github.io/paper-date-picker/web-animations-js/web-animations-next-lite.min.js:15:30159)
    at b.AnimationTimeline.play (http://bendavis78.github.io/paper-date-picker/web-animations-js/web-animations-next-lite.min.js:15:30354)
    at HTMLElement._runAnimationEffects (http://bendavis78.github.io/paper-date-picker/neon-animation/neon-animation-runner-behavior.html:56:32)b.newUnderlyingAnimationForKeyframeEffect @ keyframe-effect-constructor.js:128_rebuildUnderlyingAnimation @ web-animations-next-animation.js:86b.Animation @ web-animations-next-animation.js:35_play @ timeline.js:48b.newUnderlyingAnimationForGroup @ group-constructors.js:189_rebuildUnderlyingAnimation @ web-animations-next-animation.js:90b.Animation @ web-animations-next-animation.js:35_play @ timeline.js:48play @ timeline.js:65_runAnimationEffects @ neon-animation-runner-behavior.html:56playAnimation @ neon-animation-runner-behavior.html:81_onIronSelect @ neon-animated-pages.html:175handler @ VM33 polymer.html:516fire @ VM33 polymer.html:1272_applySelection @ iron-selectable.html:331setItemSelected @ VM57 iron-selection.html:84select @ VM57 iron-selection.html:103_selectSelected @ iron-selectable.html:279_updateSelected @ iron-selectable.html:275_complexObserverEffect @ VM33 polymer.html:1573_effectEffects @ VM33 polymer.html:1402_propertySetter @ VM33 polymer.html:1386setter @ VM33 polymer.html:1465_selectPage @ paper-date-picker.html:283_tapHeadingYear @ paper-date-picker.html:278handler @ VM33 polymer.html:516fire @ VM33 polymer.html:1272fire @ VM33 polymer.html:853forward @ VM33 polymer.html:1143click @ VM33 polymer.html:1128handleNative @ VM33 polymer.html:743
</pre>

**Comment by jenishngl** [comment] 2016-11-02 11:40
+1

**Comment by petearvanitis** [comment] 2016-11-02 12:36
This doesn't look like its an issue w/ the head of the master branch. It looks like the gh-pages branch is out of date.

**Comment by rn2013** [comment] 2017-08-08 12:16
This issue is caused by web pollyfill hack in webanimations neon-animated-pages [here](https://github.com/PolymerElements/neon-animation/issues/150) and is resoved in neon-animation v1.2.3
update or install neon-animation 1.2.3 with the following command using bower
bower install --save neon-animation#1.2.3

**Comment by admwx7** [comment] 2017-09-18 23:05
Thanks @rn2013 for the fix, I've got a ticket out to remove neon-animations since it's deprecated so I'm going to close this issue out.

**Closed by admwx7** 2017-09-18 23:05 UTC
