### ISSUE TITLE
Demo - unable to select certain dates on the calendar

### ISSUE THREAD

**Issue by obe1line** [bendavis78/paper-date-picker#101] opened 2016-03-30 13:39 UTC
In the demo certain days are not selectable - appears to be the 4th row.
E.g. 
March 24th, 31st 2016
April 21st, 28th 2016

Selecting the year on the left pane and changing it allows those dates to be selected in some cases and other dates cannot be selected.

Reproduce on Chrome browser by:
1) Browse to the demo at http://bendavis78.github.io/paper-date-picker/paper-date-picker/
2) The date is the 13th April 2017 and the 27th cannot be selected.
3) Change the year by clicking the year in the left pane. Select 2018, now all dates can be selected.
4) Select the 27th then change the year back to 2017.
5) Now all dates can be selected apart from the 13th and 21st.
6) Repeat changing dates and years to change the dates that cannot be selected.

**Comment by johnlim** [comment] 2016-04-07 10:01
Yup, it's happening on my end too though on different dates.

**Comment by johnlim** [comment] 2016-04-07 10:31
The un-clickable dates seem to have a styling issue as their width are 0px versus the clickable ones which have a width of 28px. Correcting that in chrome developer tools resulted in it being clickable. I haven't had the chance to look into the code to root cause the problem but it might provide some insight for those following this issue.

**Comment by johnlim** [comment] 2016-04-08 08:35
PR #100 fixes this issue but I guess we'll have to wait for @bendavis78 to see if its an acceptable fix. In the meantime, shifting `on-tap="_tapDay"` to its parent element also works around this issue.

**Comment by bendavis78** [comment] 2016-04-17 18:18
Fixed in PR #100.

**Closed by bendavis78** 2016-04-17 18:18 UTC
