### ISSUE TITLE
Problems in Firefox

### ISSUE THREAD

**Issue by petersonb** [bendavis78/paper-date-picker#118] opened 2016-06-06 19:10 UTC
Using Firefox 38.8.0

I cannot move forward or back more than one month when selecting a date. (June <- July -> August)

When I select date one month forward or back (as far as I can go either way), when I click the day, it scrolls like would if returning to the original month. However, it does change the month and select the correct day.

Summary: Selecting dates in Firefox, I can only select on month forward or back, and have to "scoot" from month to month to get anywhere. Working in Chrome just fine in same App. Recreated using provided component page.

**Comment by mercmobily** [comment] 2016-07-10 07:37
I can confirm this. Plus, if you move month, and then resize the window, the month slides back to the previous month. This is a pretty big show-stopper for this otherwise great component!

**Comment by miguelcp646** [comment] 2016-07-11 13:45
I think this is a duplicate of #91, which is already fixed. The problem is there's still no release with this fix.

**Comment by bendavis78** [comment] 2016-08-07 21:12
Sorry for all the delay, this should be included in 1.1.5.

**Closed by bendavis78** 2016-08-07 21:12 UTC
