### ISSUE TITLE
Setting min-date and max-date gives an error !!!

### ISSUE THREAD

**Issue by divyayogesh** [bendavis78/paper-date-picker#94] opened 2016-03-18 13:23 UTC
I was trying to set a date range. That is min-date as Tomorrow (today+1 ) and Max Date as (Today +5 days).
Giving this error--
** Date outside of valid range: Fri Mar 18 2016 18:43:58 GMT+0530 (IST)**
**polymer.html:1491 Uncaught RangeError: Maximum call stack size exceeded**

**Comment by bendavis78** [comment] 2016-04-17 17:32
Duplicate of #81

**Closed by bendavis78** 2016-04-17 17:32 UTC
Labels: duplicate
