### ISSUE TITLE
neon-animated-pages garbled

### ISSUE THREAD

**Issue by vitalygoji** [bendavis78/paper-date-picker#90] opened 2016-03-10 07:35 UTC
![neon](https://cloud.githubusercontent.com/assets/1196926/13662506/e0b3215a-e64f-11e5-9e3f-530af1dcc1cf.png)
In chrome "neon-animated-pages" portion of component is garbled. If I open/close developer tools things get normal.
I tried to repaint component, change styles in dev tools, add new elements to force redraw, nothing works except opening / closing dev tools.
Anyone had same issue?

**Comment by bendavis78** [comment] 2016-03-13 01:02
Duplicate of #43

**Closed by bendavis78** 2016-03-13 01:02 UTC
Labels: duplicate
